### ISSUE TITLE
Please provide diagram of project folder structure assumed

### ISSUE THREAD

**Issue by elliotrock** [tqc/codedeploy-scripts#3]
Hi, 

Your assumptions are a bit vague, please could your define a node folder structure that you base this assumptions on. Is it?:

build/
      - "your node project"
static/
      - "media assets?"
app/
     - yourApp/
           - _where the file app will be deployed to on AWS?_

**Comment by tqc** [comment]
See https://github.com/tqc/react-demo for a minimal working example. 

./static and ./build are intended for static files that can be served directly by nginx; if nothing in there matches the requested url, the request goes through to the node process.

**Comment by elliotrock** [comment]
thank you
