### ISSUE TITLE
Fail on EC2 folder structure

### ISSUE THREAD

**Issue by elliotrock** [tqc/codedeploy-scripts#4]
The location or/and folder structure may not be correct for a typical ec2 folder structure

**#!/usr/bin/env node**

Fails with below log:

Error CodeScriptFailed
Script Namedeployment.js
MessageScript at specified location: deployment.js failed with exit code 127
Log TailLifecycleEvent - BeforeInstall
Script - deployment.js
[stderr]/usr/bin/env: node: No such file or directory

**Comment by tqc** [comment]
Do you have node installed on your ec2 instance? See the userdata link I just added to the readme

**Comment by elliotrock** [comment]
Yes and npm.

**Comment by tqc** [comment]
Which base image are you using? I haven't used ubuntu in a while, but it certainly used to have issues with installing node as something else to avoid naming conflicts.

See https://github.com/nodejs/node-v0.x-archive/issues/3911

**Comment by elliotrock** [comment]
Amazon Linux. The path to the node installation is **/home/ec2-user/node**

This image has all the aws cli tools etc...

**Comment by tqc** [comment]
That would be the problem - anything you install and test manually runs as ec2-user, but the codedeploy agent runs as root and won't see anything in the user path.

**Comment by elliotrock** [comment]
Yup time to use those free AWS support credits. I post fixes here to help other.

Thanks for your quick and useful responses.
