### ISSUE TITLE
codedeploy-scripts not found during deployment

### ISSUE THREAD

**Issue by elliotrock** [tqc/codedeploy-scripts#5]
On deployment  the _codedeploy-scripts_ module is not found.

Do I need to add this to my package.json ?

**Comment by tqc** [comment]
Of course, same as any node module. You'll also need to make sure that npm install has run before creating the codedeploy package; running npm on the server won't work with the default setup, though in theory you could wrap deployment.js in another script that calls npm install first.

**Comment by elliotrock** [comment]
Solved the note on npm didn't have the --save. SO now it is in the
 project

**Comment by elliotrock** [comment]
thanks again
